# Generated by Django 5.2 on 2025-04-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_alter_mentorados_estagio_disponibilidadehorarios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadehorarios',
            options={'verbose_name': 'horarios', 'verbose_name_plural': 'horarios'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name': 'reunioes', 'verbose_name_plural': 'reunioes'},
        ),
        migrations.AlterModelTable(
            name='disponibilidadehorarios',
            table='horarios',
        ),
        migrations.AlterModelTable(
            name='reuniao',
            table='reunioes',
        ),
    ]
