# Generated by Django 5.2 on 2025-04-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0005_tarefa_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'verbose_name': 'tarefa', 'verbose_name_plural': 'tarefas'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': 'upload', 'verbose_name_plural': 'uploads'},
        ),
        migrations.AlterModelTable(
            name='tarefa',
            table='tarefas',
        ),
        migrations.AlterModelTable(
            name='upload',
            table='upload',
        ),
    ]
